files:
  include: '**/*.scss'
  ignore: '**/node_modules/**'
options:
  formatter: stylish
rules:
  attribute-quotes: 2
  bem-depth:
    - 2
    - max-depth: 3
  border-zero: 1
  brace-style: 2
  class-name-format: 2
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: true
  empty-line-between-blocks: 1
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format: 2
  indentation: 1
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 1
    - length: 300
  max-line-length:
    - 1
    - length: 150
  mixin-name-format: 2
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 3
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 1
  no-debug: 2
  no-disallowed-properties: 0
  no-disallowed-property-values: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 1
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 1
  placeholder-name-format: 1
  property-sort-order:
    - 1
    - order: 'concentric'
  property-units:
    - 1
    - global: ['px', 'rem', 's']
  pseudo-element: 2
  quotes:
    - 2
    - style: 'single'
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 1
  variable-name-format: 2
  zero-unit: 2
